micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: jdbc:mysql://localhost:3306/casadocodigoKotlinDB?useTimezone=true&serverTimezone=UTC
    username: root
    password: bancoroot
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true